Repository prove-rs/z3.rs, pull requests merged in 2025-08, with the labels that each got.

#401 changed!: refcount z3 context
  z3/src/ast.rs
  z3/src/context.rs
  z3/src/datatype_builder.rs
  z3/src/func_decl.rs
  z3/src/func_entry.rs
  z3/src/func_interp.rs
  z3/src/goal.rs
  z3/src/lib.rs
  z3/src/model.rs
  z3/src/ops.rs
  z3/src/optimize.rs
  z3/src/params.rs
  z3/src/pattern.rs
  z3/src/probe.rs
  z3/src/rec_func_decl.rs
  z3/src/solver.rs
  z3/src/sort.rs
  z3/src/statistics.rs
  z3/src/symbol.rs
  z3/src/tactic.rs
  z3/tests/lib.rs
  z3/tests/ops.rs
Labels: refactor

#394 Move Model Retrieval Docs
  z3/src/solver.rs
Labels: doc

#392 Add Constructors for Floating-Point NaN Values
  z3/src/ast/float.rs
Labels: enhancement

#390 Add Sequence::empty and contains Methods
  .gitignore
  z3/src/ast/seq.rs
Labels: enhancement

#410 feat!: trait-based conversions and operations
  z3/src/ast/array.rs
  z3/src/ast/bool.rs
  z3/src/ast/bv.rs
  z3/src/ast/float.rs
  z3/src/ast/int.rs
  z3/src/ast/mod.rs
  z3/src/ast/real.rs
  z3/src/ast/regexp.rs
  z3/src/ast/rounding_mode.rs
  z3/src/ast/seq.rs
  z3/src/ast/set.rs
  z3/src/ast/string.rs
  z3/src/model.rs
  z3/src/ops.rs
  z3/src/solver.rs
  z3/src/translate/synchronization/mod.rs
  z3/tests/lib.rs
  z3/tests/objectives.rs
  z3/tests/ops.rs
  z3/tests/semver_tests.rs
Labels: enhancement

#389 chore: add unit tests for rounding modes
  z3/tests/lib.rs
Labels: enhancement

#425 feat(z3-sys): do not depend on std
  z3-sys/src/lib.rs
Labels: enhancement, refactor
